version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: ${PORT}
      DEFAULT_API_PREFIX: ${DEFAULT_API_PREFIX}
      NODE_ENV: ${NODE_ENV}
      PLATFORM: ${PLATFORM}
      API_KEY: ${API_KEY}
    volumes:
      - .:/src/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
