version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .docker.env
    volumes:
      - .:/src/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
